# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbelt', '0003_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quoteuser', to='pbelt.User'),
            preserve_default=False,
        ),
    ]
